### ISSUE TITLE
Connect to Oracle SQL Database

### ISSUE THREAD

**Issue by KiChjang** [KiChjang/Bloggitor#1]
By default, the Rails application uses an sqlite3 database. We will need to change this to use SoC's Oracle database with the credentials given to us. This would most likely involve installing a new Ruby gem that acts as the adapter to the Oracle database.

**Comment by KiChjang** [comment]
This isn't as easy as I thought... the documentation provided in the IVLE, titled "A Guide to Connecting to SoC Oracle Server", tells us that we will need a VPN connection in order to connect to SoC's Oracle SQL server.

I have half a mind to change to an easier solution, namely SQL server, since I had experience using it.

**Comment by KiChjang** [comment]
Or, we use PostgreSQL/MySQL during development, and switch to Oracle SQL in production. But that does not alleviate the setup difficulty when we are in production.

**Comment by jinified** [comment]
Thats why i prefer mysql server just because relying on the school oracle can be a hassle at time

**Comment by KiChjang** [comment]
I'm going to go ahead and use PostgreSQL for now, since Heroku uses it.
